name: Bitcoin order App
on:
  push:
    branches:
      - githubcicd
      - feature/mlops-demo

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-cache-node-modules-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci --force

      - name: Build
        run: npm run build -- --base-href=/bitcoin-order-app/

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd dist/bitcoin
          touch .nojekyll
          git init
          git add -A
          git commit -m "deploy to GitHub Pages"
          git branch -M gh-pages
          git push -f https://oauth2:${GH_TOKEN}@github.com/${{ github.repository }}.git gh-pages
